-- HAND-VERIFIED (2026-05-26): CHECK constraint added manually — drizzle-kit cannot emit CHECK on numeric columns.
-- Generated by drizzle-kit generate, renamed from 0004_smooth_miss_america.sql.
-- See Plan 07-02: T-07-02 threat mitigation — hakedis_period_lines_cumulative_check guards against retroactive qty manipulation.
-- WARNING: Do NOT re-run drizzle-kit generate on this file — the CHECK constraint will be dropped.
CREATE TABLE "hakedis_period_lines" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid,
	"period_id" uuid NOT NULL,
	"boq_item_id" uuid NOT NULL,
	"material_snapshot" text NOT NULL,
	"unit_snapshot" text NOT NULL,
	"currency_code_snapshot" text NOT NULL,
	"unit_price_snapshot" numeric(15, 4) NOT NULL,
	"cumulative_qty_approved" numeric(12, 3) NOT NULL,
	"previous_cumulative_qty" numeric(12, 3) DEFAULT '0' NOT NULL,
	"period_qty" numeric(12, 3) NOT NULL,
	"period_value" numeric(15, 2) NOT NULL,
	"cumulative_value" numeric(15, 2) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hakedis_periods" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid,
	"project_id" uuid NOT NULL,
	"period_number" text NOT NULL,
	"period_start_date" date,
	"period_end_date" date NOT NULL,
	"currency_code" text DEFAULT 'TRY' NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"notes" text,
	"kdv_rate" numeric(5, 4) DEFAULT '0.2000' NOT NULL,
	"retention_rate" numeric(5, 4) DEFAULT '0.0500' NOT NULL,
	"created_by_user_id" text,
	"finalized_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "office_activity_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid,
	"actor_user_id" text NOT NULL,
	"action_type" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" text,
	"project_id" uuid,
	"metadata" jsonb,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "boq_items" ADD COLUMN "unit_price" numeric(15, 4);--> statement-breakpoint
ALTER TABLE "boq_items" ADD COLUMN "currency_code" text DEFAULT 'TRY' NOT NULL;--> statement-breakpoint
ALTER TABLE "hakedis_period_lines" ADD CONSTRAINT "hakedis_period_lines_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hakedis_period_lines" ADD CONSTRAINT "hakedis_period_lines_period_id_hakedis_periods_id_fk" FOREIGN KEY ("period_id") REFERENCES "public"."hakedis_periods"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hakedis_period_lines" ADD CONSTRAINT "hakedis_period_lines_boq_item_id_boq_items_id_fk" FOREIGN KEY ("boq_item_id") REFERENCES "public"."boq_items"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hakedis_periods" ADD CONSTRAINT "hakedis_periods_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hakedis_periods" ADD CONSTRAINT "hakedis_periods_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hakedis_periods" ADD CONSTRAINT "hakedis_periods_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "office_activity_log" ADD CONSTRAINT "office_activity_log_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "office_activity_log" ADD CONSTRAINT "office_activity_log_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "office_activity_log" ADD CONSTRAINT "office_activity_log_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "hakedis_period_lines_period_idx" ON "hakedis_period_lines" USING btree ("period_id");--> statement-breakpoint
CREATE INDEX "hakedis_period_lines_boq_idx" ON "hakedis_period_lines" USING btree ("boq_item_id");--> statement-breakpoint
CREATE INDEX "hakedis_periods_project_idx" ON "hakedis_periods" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "hakedis_periods_status_idx" ON "hakedis_periods" USING btree ("status");--> statement-breakpoint
CREATE INDEX "hakedis_periods_currency_idx" ON "hakedis_periods" USING btree ("project_id","currency_code");--> statement-breakpoint
CREATE INDEX "office_activity_log_actor_idx" ON "office_activity_log" USING btree ("actor_user_id");--> statement-breakpoint
CREATE INDEX "office_activity_log_project_idx" ON "office_activity_log" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "office_activity_log_action_idx" ON "office_activity_log" USING btree ("action_type");--> statement-breakpoint
CREATE INDEX "office_activity_log_occurred_idx" ON "office_activity_log" USING btree ("occurred_at");--> statement-breakpoint
-- HAND-EDITED: drizzle-kit cannot emit CHECK constraints on numeric columns.
-- Prevents negative period quantities / retroactive quantity manipulation (T-07-02 double-billing guard).
-- Enforces yeşil defter (cumulative ledger) invariant: current cumulative >= previous cumulative.
ALTER TABLE "hakedis_period_lines"
  ADD CONSTRAINT "hakedis_period_lines_cumulative_check"
  CHECK (cumulative_qty_approved >= previous_cumulative_qty);
